services:
  # Development service
  chatbot-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  # Production service
  chatbot-frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
    profiles:
      - prod

  # Build service (for CI/CD)
  chatbot-frontend-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    profiles:
      - build 